name: First-Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print Greeting
        run: echo "Welocme to Github Actions"
      - name: Good bye Greeting
        run: echo "Job Done Bye !!!!!!!!!!!"
